channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - scipy
  - rdkit
  - gemmi
  - meeko==0.6.1
  - vina
  - autogrid
  - cctbx-base=2025.6
  - jupyter
  - jupyterlab
  - ipywidgets
  - matplotlib
  - pandas
  - biopython
  - pip
  - pip:
    - py3Dmol
    - molscrub
